# Site settings
baseurl: /documentation
permalink: /:categories/:title/

# Defaults for posts
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: page
      weight: 50

# Jekyll
exclude:
  - Readme.md
  - Guardfile
  - Gemfile
  - Gemfile.lock
collections:
  faq:
    permalink: /faq/:title/
    output: true

# SASS
sass:
  sass_dir: _sass
  style: :compressed

# Build settings
markdown: kramdown
