# Site settings
baseurl: /documentation

# Jekyll
gems:
  - jekyll-slim
exclude:
  - Readme.md
  - Guardfile
collections:
  faq:
    permalink: /faq/:title/
    output: true

# Slim
slim:
  pretty: true

# SASS
sass:
  sass_dir: _sass
  style: :compressed

# Build settings
markdown: kramdown
permalink: pretty
