# Site settings
baseurl: /documentation
permalink: /:categories/:title/

# Jekyll
exclude:
  - Readme.md
  - Guardfile
  - Gemfile
  - Gemfile.lock
collections:
  faq:
    permalink: /faq/:title/
    output: true

# SASS
sass:
  sass_dir: _sass
  style: :compressed

# Build settings
markdown: kramdown
