# Site settings
url: https://documentation.codeship.com
baseurl:
permalink: /:categories/:title/
tags_dir: tags
ubuntu_version: trusty

# Defaults for posts
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: posts
    values:
      layout: page
      weight: 50
      comments: true

# Jekyll
exclude:
  - _*.json
  - bin
  - CODE_OF_CONDUCT.md
  - codeship-services.yml
  - codeship-steps.yml
  - codeship.aes
  - CONTRIBUTING.md
  - external
  - Gemfile*
  - Guardfile
  - gulpfile.js
  - LICENSE.md
  - node_modules
  - npm-shrinkwrap.json
  - package.json
  - README.md
  - templates
encoding: utf-8
gems:
  - jekyll-coffeescript
  - jekyll-seo-tag
  - jekyll-sitemap
collections:
  faq:
    permalink: /faq/:path/
    output: true

# SASS
sass:
  sass_dir: _sass
  style: :compressed

# Build settings
markdown: kramdown

# Kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    line_numbers: false

# Prose.io
prose:
  rooturl: '_posts'
  siteurl: 'https://documentation.codeship.com/'
  media: 'images'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: 'layout'
        field:
          element: 'hidden'
          value: 'page'
      - name: 'title'
        field:
          element: 'text'
          label: 'Page Title'
      - name: 'categories'
        field:
          element: 'select'
          label: 'Category'
          options: 'https://documentation.codeship.com/metadata/categories.jsonp'
      - name: 'tags'
        field:
            element: 'multiselect'
            label: 'Tags'
            placeholder: 'Choose Tags'
            alterable: true
            options: 'http://documentation.codeship.com/metadata/tags.jsonp'
      - name: 'weight'
        field:
          element: 'number'
          label: 'Page Weight'
          help: 'Used for sorting subpages in listings'
          value: 50
